# Site settings
title: Sports&GO
email: info@sportsgo.net
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

# User setting
owner: Sports&Go
email: info@sportsgo.net
facebook_username: 
twitter_username:
github_username: 
address: 
  - line: Porto
  - line: Portugal
  # Feel free to add more lines here 
telephone:
copyright: xpto

# API settings
google_api_key: AIzaSyCRngKslUGJTlibkQ3FkfTxj3Xss1UlZDA

# Build settings
markdown: kramdown