# Site settings
title: Sports & GO
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

# User setting
owner: Sports & GO
email: info@sportsgo.net
facebook_username: 
twitter_username:
github_username:
linkedin_username: sports&go
address: 
  - line: Porto - Portugal
  # Feel free to add more lines here 
#telephone:
copyright: Sports&GO

# API settings
google_api_key: AIzaSyAzOT2pa_MwVQ3eau8wIhbYpBuOvHILN40

# Build settings
markdown: kramdown
